### PR TITLE
Implementing eq.rewrite(Add)

### PR DESCRIPTION
**Pull request by Davide-sd**
There are occasions in which it is useful to rewrite `Equation(L, R)` either as `Equation(L-R, 0)`
or as a symbolic expression `L-R`. For example:

```
from sympy import *
from algebra_with_sympy import Equation
DT = symbols(r"\Delta{T}")
alc, als = symbols("alpha_c, alpha_s")
sc, ss = symbols("sigma_c, sigma_s")
E, Ac, As = symbols("E, A_c, A_s")
eq = Equation(alc * DT + sc / E, als * DT - Ac * sc / (As * E))

# with the new feature
eq.rewrite(Add).collect(sc).collect(DT)

# old way: longer to type
Equation(eq.lhs - eq.rhs, 0).collect(sc).collect(DT)
```

The implementation borrowed code from `sympy.core.relational.Equality._eval_rewrite_as_Add`.
This should provide a more consistent user-experience for people that are used to such functionality.

### CODE REVIEW

**Comment by gutow** [comment]
@Davide-sd, thanks for the pull request.

I am not sure why you need the added complexity. The following statement does the same thing as the way you are using rewrite. I think this is better because it is more like doing math on paper, so does not require learning a special sympy syntax.
```
eq - eq.rhs
```
will yield and equation with everything on the lhs and zero on the rhs.

And you can, of course, do similar things with other operations:
```
eq/eq.rhs

eq*eq.rhs

eq**eq.rhs
```

You can duplicate the behavior of your example with the more natural syntax and no rewrite:
```
from sympy import *
from algebra_with_sympy import Equation
DT = symbols(r"\Delta{T}")
alc, als = symbols("alpha_c, alpha_s")
sc, ss = symbols("sigma_c, sigma_s")
E, Ac, As = symbols("E, A_c, A_s")
eq = Equation(alc * DT + sc / E, als * DT - Ac * sc / (As * E))

(eq - eq.rhs).collect(sc).collect(DT)
```
This is actually a little shorter than your example using `rewrite`. However, that does not mean we shouldn't include `rewrite` if there is something it can do that cannot be done using a more on-paper-like syntax. I would like to see some other examples of where this is useful.

**Comment by gutow** [comment]
One other thing. It does not appear that the implementation of `rewrite` can easily handle the case where you want to go the other direction as in:
```
eq - eq.lhs
```
Which makes the lhs  zero instead of the rhs.

I think you would have to do:
```
eq.rewrite(Add).swap
```

**Comment by Davide-sd** [comment]
Your arguments are very good, but the PR addressed the die-hard old habit inherited from years of SymPy usage, in particular the limitations of SymPy's `Eq` which doesn't support mathematical operations. So, as long as SymPy solvers throws out an `Eq` obect, `rewrite(Add)` will always be the first thing that comes to my mind to do such operation.

**Comment by gutow** [comment]
> the PR addressed the die-hard old habit inherited from years of SymPy usage,

@Davide-sd am I correct in understanding that you are arguing that experienced sympy users are more likely to adopt algebra_with_sympy if it also supports things that people used because that was the best way in sympy, even when there is a more natural alternative?

I also have on my list to get `Equation(Equality)` to return an Equation.

**Comment by Davide-sd** [comment]
> am I correct in understanding that you are arguing that experienced sympy users are more likely to adopt algebra_with_sympy if it also supports things that people used because that was the best way in sympy, even when there is a more natural alternative?

That's what I believe. While experienced users are likely going through the documentation of a new data type (at least once) and find a suitable example, it is also true that old habits are difficult to replace.

I agree that `eq - eq.rhs` is more natural. However, I've already encountered occasions in which I have to use long variable names for the equations (to keep track of what they do). When a longer name is used, then rewrite is just faster to type:

```
my_long_eq_name.rewrite(Add)
my_long_eq_name - my_long_eq_name.rhs
```

**Comment by gutow** [comment]
> However, I've already encountered occasions in which I have to use long variable names for the equations (to keep track of what they do). When a longer name is used, then rewrite is just faster to type:
> 
> ```
> my_long_eq_name.rewrite(Add)
> my_long_eq_name - my_long_eq_name.rhs
> ```

Excellent point! I'm convinced this should be included for the power users, just by this. Two other things I am worried about:

1. I think this also needs a couple of tests verifying that it doesn't break the normal behavior of rewrite. I don't want to get bitten by having something like the following stop working:
```
>>> var('theta')
>>> eq1 = Eqn(exp(I*theta),cos(theta) + I*sin(theta))
>>> eq1.rewrite(exp)
Equation(exp(I*theta), exp(I*theta))
```
2. I am worried about this potential deprecation warning in the docstring of Expr.rewrite:
```
Defining ``_eval_rewrite_as_[...]()`` method is supported for backwards
compatibility reason. This may be removed in the future and using it is
discouraged.
````
I have no sense of how important the warning is.

@Davide-sd I also want to thank you for the rewrites of the tests for the experimental `solve()` behavior.

**Comment by Davide-sd** [comment]
> I think this also needs a couple of tests ...
> I am worried about this potential deprecation warning ...

Very good points! I'll give it a deeper look in the next few days! :)

**Comment by gutow** [comment]
@Davide-sd FYI - I just pushed my latest developments to master. This is the beginnings of the updates to test the overriding of sympy functions. You may want to base any tests for the `rewrite` on this modified testing code.

**Comment by Davide-sd** [comment]
> I am worried about this potential deprecation warning in the docstring of Expr.rewrite:

Which version of SymPy are you using? I tried to search for this deprecation warning with `grep` inside Sympy 1.11.dev, but I couldn't find it...

**Comment by Davide-sd** [comment]
@gutow Please, take a look at the `NOTE` inside `test_rewrite`...

**Comment by gutow** [comment]
> @gutow Please, take a look at the `NOTE` inside `test_rewrite`...

I do have an idea on why you need to import the sympy specific `exp` to get the test to work in pytest. Pytest does a lot of namespace manipulation to get things to work. If you look at the tests in test_extension_of_sympy_functions.py, you will see that I could not write things to work where the function extensions were embedded in `def test_..`. because of this. I had to import functions specifically into the global namespace of the file and extend them there for things to work.   I think what is happening is that the test is operating in a namespace where we have the sympy `exp` defined, but not the one extended for Equations. I will have to think on how to access the correct function for testing.

**Comment by gutow** [comment]
@Davide-sd I think I have a handle on the source of the test failure on `rewrite(exp)`.
In vanilla python or Jupyter you get the following:
```
>>> x = symbols("x")
>>> eq = Equation(exp(I*x),cos(x) + I*sin(x))
>>> eq.rewrite(exp) == Equation(exp(I*x), exp(I*x))
False
```
The reason it is False is that the second `exp(` is from the `Basic.rewrite`, which internally uses the unextended `exp`. In retrospect this is the expected behavior because of how sympy internally uses and imports its internal classes. If algebra_with_sympy were part of sympy this problem would not occur. 

The following looks OK, but actually isn't because of the above issue:
```
>>> eq.rewrite(exp)
Equation(exp(I*x), exp(I*x))
```
The current implementation of `solve()` also has the same problem.
```
 eq2 = Eqn(a,exp(x))
>>> solve(eq2, x)[0] == Eqn(x, log(a))
x = log(a)
False
```
It does work with just sympy:
``` 
>>>from sympy import *
>>>var('a x')
(a, x)
>>> result = solve(a-exp(x),x)
>>> result
[log(a)]
>>> result[0] == log(a)
True
```
I am actually not clear how much of a problem this is. I can only imagine it causing problems if there is some way to apply one of these unextended sympy functions to an equation. I have not figured out a way to do that. **Can you?**

If you cannot either I am inclined to incorporate things as they are and see if people run up against a problem caused by this.

**Comment by gutow** [comment]
@Davide-sd Have you thought of any way one of these unextended sympy functions can apply to an equation? I still haven't. If you have not either, I think we should fix the conflicts and then it can be merged.

>I think I have a handle on the source of the test failure on `rewrite(exp)`. In vanilla python or Jupyter you get the following:
> 
> ```
> >>> x = symbols("x")
> >>> eq = Equation(exp(I*x),cos(x) + I*sin(x))
> >>> eq.rewrite(exp) == Equation(exp(I*x), exp(I*x))
> False
> ```
> 
> The reason it is False is that the second `exp(` is from the `Basic.rewrite`, which internally uses the unextended `exp`. In retrospect this is the expected behavior because of how sympy internally uses and imports its internal classes. If algebra_with_sympy were part of sympy this problem would not occur.
[snip]
> I am actually not clear how much of a problem this is. I can only imagine it causing problems if there is some way to apply one of these unextended sympy functions to an equation. I have not figured out a way to do that. **Can you?**
> 
> If you cannot either I am inclined to incorporate things as they are and see if people run up against a problem caused by this.

**Comment by Davide-sd** [comment]
> Have you thought of any way one of these unextended sympy functions can apply to an equation? I still haven't. If you have not either, I think we should fix the conflicts and then it can be merged.

I haven't. This week I put the module through some relatively extensive practical use and I haven't had any problems related to this "issue". I think you are good to merge this PR.

**Comment by gutow** [comment]
Thanks for the fixing the conflicts. Squashing and merging.

**Pull request merged**
