### PR TITLE
Use  hooks to IPython display formatter and sys.displayhook to simplify control of human readable output.

### PR DESCRIPTION
**Pull request by gutow**
## This Simplifies Controlling the Format of Interactive Outputs
* **Sympy expressions and Equations now behave the same.** See below.

* **In graphical environments (Jupyter)** you will get rendered Latex such as 
$\frac{a}{b} = \frac{c}{d}$. To also see the code representation (what can 
  be copied and pasted for additional computation) set 
 `algwsym_config.output.show_code = True`. 
  This will print the code version (e.g. `Equation(a,b/c)`) of the equation as 
  well. This code version can be accessed directly by calling `repr()` on the 
  equation.

* **In interactive text environments (IPython and command line)** the 
  human readable version is returned by default. To have the code version
 returned by default set `algwsym_config.output.human_text=False`. To see
both the code and human readable versions set both 
`algwsym_config.output.human_text` and
 `algwsym_config.output.show_code` to `True`.

* **The equation label** can be turned off by setting
  `algwsym_config.output.label = False`.

* **Solve now behaves like any other Sympy operation**. It defaults to human
  readable output, which can be turned off. 
  * To get human readable and
  code versions set both `algwsym_config.output.human_text` and
  `algwsym_config.output.show_code` to `True`.

  * `algwsym_config.output.solve_to_list = True` causes solve() to return solutions sets as Python lists. Using this option prevents pretty-printing of the solutions produced by solve(), but recovers the behavior of experimental versions of `solve()` before version 0.11.0.

### CODE REVIEW

**Comment by gutow** [comment]
@Davide-sd Thanks for your help in the past on the Algebra_with_Sympy package. I would appreciate your help again, because I had an idea which impacts how `solve` works.

I figured out how to inject output before Sympy output in a way that I think simplifies using Algebra_with_Sympy and removes the extra complication of separate output controls for the `solve` operation. I have included it in this pull-request. Before I put effort into making nice documentation of how this works, could you look at this and let me know if this would work for you, rather than the more complicated special output controls we came up with for `solve`?

To make this work, I did have to override Sympy's standard way of outputting  a `FiniteSet()` which does not produce a representation  that can be copy and pasted to get back a `FiniteSet()`. That works in this pull-request.

Thanks,
Jonathan

**Comment by Davide-sd** [comment]
Hello Jonathan, everything looks good to me. One question: why did you  wrapped the output of `solve` into a `FiniteSet`, instead of getting an ordinary list? It requires a further conversion step to a list in order to get results out of it.

**Comment by gutow** [comment]
> One question: why did you wrapped the output of `solve` into a `FiniteSet`, instead of getting an ordinary list? It requires a further conversion step to a list in order to get results out of it.

Davide, thanks for looking at this. 

The main reason I wrapped it in `FiniteSet` is that this forces pretty-printing of the solutions, which allows the much simpler control of the output. If you return a python list the solutions do not pretty-print. Wrapping solutions in `FiniteSet` also guarantees that the code version of solutions can be copied and pasted to get a Sympy compatible expression (see https://github.com/sympy/sympy/pull/24574, for some discussion of the behavior of `FiniteSet` and Sympy). There is actually a pretty simple way to get the elements. `set.args[i]` will return element i of the `FiniteSet`. Alternatively, `list(set)[i]` works. The major problem with these sets is there are no guarantees that the element order will be the same each time.

How big a problem is`set[i]` not working , in your opinion?

**Comment by gutow** [comment]
> Ehh, I developed some code that relies on the output to be a list. Would it be possible to add a configuration option and let the user decide the output type? For example, `algwsym_config.output.finiteset = True` returns a `FiniteSet`, otherwise it returns a list. Doing so, I can adjust my code with a single line, instead of manually adjusting hundreds of occurrences...

@Davide-sd I think I can easily do something like that. I will let you know when I have an adjustment you can check against your code.

Thanks for the input.

**Comment by Davide-sd** [comment]
> Or do you want each `FiniteSet()` of solution sets replaced with `list()` as well?

This one, so that it would be fully back-compatible!

**Comment by gutow** [comment]
> > Or do you want each `FiniteSet()` of solution sets replaced with `list()` as well?
> 
> This one, so that it would be fully back-compatible!

@Davide-sd please try the most recent commit versus your code to see if I have got everything. The behavior is now:
```
    >>> eq1 = Eqn(abs(2*x+y),3)
    >>> eq2 = Eqn(abs(x + 2*y),3)

    Pre-0.11.0 behavior where a python list of solutions is returned
    >>> algwsym_config.output.solve_to_list = True
    >>> solve((eq1,eq2))
    [[Equation(x, -3), Equation(y, 3)], [Equation(x, -1), Equation(y, -1)], [Equation(x, 1), Equation(y, 1)], [Equation(x, 3), Equation(y, -3)]]
```

**Comment by Davide-sd** [comment]
@gutow thank you for your work, everything is fine now :)

**Pull request merged**
