### PR TITLE
Implemented eq1.subs(eq2)

### PR DESCRIPTION
**Pull request by Davide-sd**
Sometime it is useful to take one equation and substitute it into another one. For example:

```
eq1 = Equation(L1, R1)
eq2 = Equation(L2, R2)
eq1.subs(eq2)
```

The above code will look for L2 inside L1 and R1: if matches are found, they will be replaced
with R2. This feature is very important for this class to be used "naturally" and quickly.
The obvious alternative would be to execute:

```
eq1.subs(eq2.lhs, eq2.rhs)
```

which is fine if we are only doing one substitution once in a while, but become time consuming
when dealing with multiple equations and multiple substitutions.

Even though the best approach would be to tweak the `Basic` class to make it recognizes `Equation`,
at this point of development it is not worth the effort. For the time being it is better to get
`Equation` overrides the `subs` method in order to implement the new behaviour. If and when this
module will be merged into sympy, then editing `Basic.subs` will be trivial.
This means that substituting an equation into a symbolic expression will fail.

### CODE REVIEW

**Comment by gutow** [comment]
@Davide-sd Thank you. You've been busy. This looks like what I was thinking about except for the fact that equations are not accepted for substitution into expressions. What do you think about overriding the `Expr.subs`? That would make things much more natural, although I think it is harder.

**Comment by gutow** [comment]
> What do you think about overriding the `Expr.subs`? That would make things much more natural, although I think it is harder.

I've thought about this a little more. I think you may be correct that what you've done is the correct initial step. I will do some manual testing. Assuming no problems, I will merge and open an issue to extend the syntax to work on expressions.

**Comment by gutow** [comment]
@Davide-sd 

Almost everything works as I expected. I did notice one thing we should consider.

What are your thoughts on this:
```
>>> ig1 = Eqn(p1*V,n1*R*T1)
>>> ig2 = Eqn(p2*V,n2*R*T2)
>>> V2 = solve(ig2,V)
V = R*T2*n2/p2
>>> ig1.subs(V2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonathan/GIT/Algebra_with_SymPy/algebra_with_sympy/algebraic_equation.py", line 643, in subs
    return super().subs(*new_args, **kwargs)
  File "/home/jonathan/.local/share/virtualenvs/Algebra_with_SymPy-ZtpO9pAV/lib/python3.10/site-packages/sympy/core/basic.py", line 940, in subs
    if isinstance(s[0], str):
TypeError: 'Equation' object is not subscriptable
```
whereas
```
>>> ig1.subs(V2[0])
Equation(R*T2*n2*p1/p2, R*T1*n1)
```
Works.

I see two possible solutions:
1. make it so the simple case of one solution does not return a list;
2. make the `.subs` override accept an iterable of equations.

This also brings up the question of whether the experimental extension of `solve` should return an array of solutions or an immutable list?

**Comment by Davide-sd** [comment]
You did a simple mistake: `solve` returns a list of solutions. You need to take the first one:

```
V2 = solve(ig2,V)[0]
print(ig1.subs(V2))
# out: R*T2*n2*p1/p2 = R*T1*n1
```

**Comment by gutow** [comment]
@Davide-sd 
> You did a simple mistake: `solve` returns a list of solutions.

I understand this, but was thinking about usability. The whole goal of algebra_with_sympy is to make it intuitive enough that people who are not familiar with programming and coding conventions can use it easily. As I also want to support power users, I lean towards extending the behavior in ways that lead to convenient behavior without breaking the power user tools.

This means I sort of lean towards:

> 2. make the .subs override accept an iterable of equations.

However, this could lead to inconsistent behavior if someone does what you call 'a simple mistake' when there are multiple solutions for one variable. I think the proper behavior would be to return a list of substituted equations.

So the behavior would be:
```
>>>eqlst = [eq1,eq2]
>>>eq3.subs(eqlst)
[eq3.subs(eq1), eq3.subs(eq2)]
```
while:
```
>>>eq3.subs(*eqlst)
eq3.subs(eq1,eq2) # following the current behavior of this pull request
```
What do you think?

**Comment by Davide-sd** [comment]
I think you need to make a decision: do you want to eventually merge this module into sympy or not? If not, you can implement whatever you want, it's your module. Otherwise, you need to accept sympy's "limitations" (or design choices), or correct them into sympy.

Regarding your question: I believe that `new_eq = eq1.subs(eq2, eq3, ...)` (as implemented in this PR) is good enough both for newbies and experts. The `subs` method (as designed in SymPy) is meant to return one single expression; by changing it to return one equation or a list of equations depending on the input arguments, you are complicating things a lot (imho), and the final user will be confused on this behavior (especially newbies).

If you want that behavior, you should implement a separate function. It is as simple as:

```
def subs_all(eq, others):
    return [eq.subs(o) for o in others]

eq1 = Eqn(L, R)
eq2 = Eqn(a, b)
eq3 = Eqn(c, d)
new_eqns = subs_all(eq1, [eq2, eq3])
```

**Comment by gutow** [comment]
@Davide-sd 
> The `subs` method (as designed in SymPy) is meant to return one single expression; by changing it to return one equation or a list of equations depending on the input arguments, you are complicating things a lot (imho)

You have a good point here. Although this package is meant primarily for interactive use, I agree that things that change the api for sympy in this way would not be a good idea and would make it less practical to incorporate it into sympy.

An alternative idea, that would help with the newbie and not get in the way of more experienced users, would be to provide a better error message if somebody passes in an iterable of equations. I am thinking about something similar to "TypeError: `.subs` does not accept a list containing elements that are `Equations`. Specify which `Equation` from the list is to be used as `list[0]`, `list[1]`, etc. If you want to use every equation in the list to substitute pass it like this `.subs(*list)` which passes each element to `.subs` as a separate argument."

If we implement your idea of `subs_all` we could also refer to that. However, the serious complication is how to handle the massive growth in number of expressions if you have multiple substitutions for multiple expressions (eg. [a = , a=, b= , b=, c=, c=].

**Comment by Davide-sd** [comment]
> An alternative idea, that would help with the newbie and not get in the way of more experienced users, would be to provide a better error message if somebody passes in an iterable of equations.

Done.

> If we implement your idea of subs_all we could also refer to that. However, the serious complication is how to handle the massive growth in number of expressions if you have multiple substitutions for multiple expressions (eg. [a = , a=, b= , b=, c=, c=].

That's why I don't like this approach. As an engineer, whenever I get multiple solutions from a `solve` command I ask myself: which solutions do I need to keep and which ones can I disregard? Filtering them before moving to the next step keeps my workflow clean, both in code (or paper) and in my mind. After the filtering, if I found myself with multiple solutions I'll analyze one by one, do the necessary steps, then go back to pickup a new solution and repeat the process. This allows me to keep focus. If I were to use the `subs_all` method I would probably get crazy to keep track of what's going on down the road.

I fear that if you implemented the `subs_all` command, (especially) newbies will be caught in the trap that you mentioned. Ultimately, they'll get stack somewhere... I think it is better for them to learn a few basic python commands (like list comprehensions, loops, ...) and let them follow their instincts, even if it means that they'll have to scratch their heads and read the docs :)

My experience is this: simplifying things is good, over-simplifying things leads to disasters and waste of time.

**Comment by gutow** [comment]
I think this is good. I am going to merge and then tweak the error message language slightly.

**Pull request merged**
