### PR TITLE
Added option to hide the output of solve command in interactive envir…

### PR DESCRIPTION
**Pull request by Davide-sd**
This solve issue #18 

Now users can set:

```
algwsym_config.output.show_solve_output = False
```

in order to hide the output of the `solve` command.

### CODE REVIEW

**Comment by gutow** [comment]
@Davide-sd I'm doing physical lab experiments today. I will try to look at this over the weekend. Also what do you think about also adding a keyword to solve so this can be done on-the-fly?

**Comment by Davide-sd** [comment]
> Also what do you think about also adding a keyword to solve so this can be done on-the-fly?

I prefer a global option (just like the one implemented by this PR) so that I change it at the beginning of the notebook and then it's done.

**Comment by gutow** [comment]
> I prefer a global option (just like the one implemented by this PR) so that I change it at the beginning of the notebook and then it's done.

I was thinking we should have both.

**Comment by gutow** [comment]
To make it work cleanly, even if we do not add an option for a flag in the solve call, I think the following additional changes are needed:
```
Index: algebra_with_sympy/__init__.py
===================================================================
diff --git a/algebra_with_sympy/__init__.py b/algebra_with_sympy/__init__.py
--- a/algebra_with_sympy/__init__.py	(revision cf438d54d14896d28e4274a348561745cb7126f4)
+++ b/algebra_with_sympy/__init__.py	(date 1673735434084)
@@ -11,6 +11,7 @@
 algwsym_config.output.show_code = False
 algwsym_config.output.human_text = False
 algwsym_config.output.label = True
+algwsym_config.output.show_solve_output = True
 
 # Set version number for internal access
 algwsym_version = 'unknown'

Index: algebra_with_sympy/algebraic_equation.py
===================================================================
diff --git a/algebra_with_sympy/algebraic_equation.py b/algebra_with_sympy/algebraic_equation.py
--- a/algebra_with_sympy/algebraic_equation.py	(revision cf438d54d14896d28e4274a348561745cb7126f4)
+++ b/algebra_with_sympy/algebraic_equation.py	(date 1673736592184)
@@ -871,7 +871,8 @@
                     if algwsym_config.output.show_solve_output:
                         display(tempeqn)
                     solnset.append(tempeqn)
-                print('-----')
+                if algwsym_config.output.show_solve_output:
+                    print('-----')
                 solns.append(solnset)
 
     else:
```

**Comment by Davide-sd** [comment]
> I think the following additional changes are needed:

Thanks for pointing it out. Done.

**Review by gutow — CHANGES_REQUESTED** [review]
[#69b635](https://github.com/gutow/Algebra_with_Sympy/pull/19/commits/69b635ef67b0a4782fb2df64375c607fab5d4aea) This will not work correctly. The `print('------')` is used to separate different solutions when there are multiple solutions. It needs to be outside the `for key in k.keys():`

**Comment by Davide-sd** [comment]
done

**Pull request merged**
